### PR TITLE
Update discord.ini to latest v10 endpoints

### PR DESCRIPTION
**Pull request by RiisDev**
Modified endpoitns to latest versions based on https://discord.com/developers/docs/topics/oauth2

### CODE REVIEW

**Comment by lairdshaw** [comment]
Thanks for the PR! A couple of quick questions:
1. Have you tested this change, and was the test successful?
2. Is it necessary or even just preferable to include the `api/v10` component? I'm just wondering whether this code would be more future-proof if it didn't stipulate a specific API version if that's possible.

If the answer to both questions is "Yes", then I'll merge this immediately, though I haven't tested myself.

**Comment by effone** [comment]
Thanks for the PR. As I can see the current code still works fine. We will be testing the changes and its result. But my opinion is to keep it approved for the future if it works and continue with current ini as long as its working. @lairdshaw ?

**Comment by RiisDev** [comment]
> Thanks for the PR. As I can see the current code still works fine. We will be testing the changes and its result. But my opinion is to keep it approved for the future if it works and continue with current ini as long as its working. @lairdshaw ?

Tested Yes it does infact work

Using the current https://discordapp.com/ endpoints are directing to v6 endpoint which is currently labeled as deprecated and may be discontinued in the future, while V10 is the current up to date and will not be discontinued/deprecated for quite awhile

https://discord.com/developers/docs/reference

**Comment by effone** [comment]
Please give us some times to test at our end and the same will be merged.
Appreciate your patience.

**Comment by lairdshaw** [comment]
>  @lairdshaw ?

I think the decision to merge after testing on our end is sound.

**Comment by Sama34** [comment]
This should be Isango getting ahead of v6 getting shut, whenever that happens

The changes seem to be reasonable, no difference should be noticeable.

**Comment by effone** [comment]
Tested. Merged.
Thanks for your contribution @RiisDev

**Pull request merged**
